### PR TITLE
Ubuntu-version and newer Ansible

### PR DESCRIPTION
**Pull request by mraygalaxy**
Hi, so I've ported this playbook to support both a newer Ansible as well as Ubuntu.

I'm not well-versed in Ansible, but I've gotten it to work. I'd prefer to have a cleaner version that uses the Ansible "package" module that knows how to switch from one linux version to another.

Would you care to help advise on how to do that?

### CODE REVIEW

**Comment by kafecho** [comment]
Hi and thanks for your contributions, that is really cool!!!!

For various reasons, I've ended up keeping CouchDB 1.6.x in production, so I have not done much work with CouchDB 2.x.

I have not used the `package` module in Ansible (some of my playbooks in production are still using Ansible 1.9). Instead of using `package` I would probably carry on using the old fashion way of using a `when` statement.

So in your main.yaml, I would do something like:

```
---
- include: main_centos.yaml
  when: ansible_distribution == "CentOS

- include: main_ubuntu.yaml
  when: ansible_distribution == "CentOS
```

In my modest Linux experience, sometimes the packages that you have to install differ quite a lot from distro to distro so it is actually simpler to write a separate task file for each version ( I also do that for roles which can run on Windows and Linux). 

I don't really use Ubuntu, so instead of trying to make the set of tasks more generic to support both OS, I would rather have 2 specialised set of files, one per OS. It would be easier for me to test. 

So if you rename your current main.yaml to be something like main_ubuntu.yaml and use the when statements above, it should work just fine.

**Comment by mraygalaxy** [comment]
Perfect. I'll give that a try =)

**Comment by mraygalaxy** [comment]
@kafecho how does it look now ..... it works for me in 5 docker containers.

**Comment by kafecho** [comment]
Looks good to me! Thanks.

**Pull request merged**
